### ISSUE TITLE
Street names don't hide after first street guess

### ISSUE THREAD

**Issue by alansartorio** [adam-lynch/back-of-your-hand#11]
I think it can be fixed by adding `isStreetsLayerShown = true;` just after this line https://github.com/adam-lynch/back-of-your-hand/blob/a38cb758f93bc8885f86b0e77da4096434395072/source/Map.svelte#L116 I haven't tested it though.

Thanks for maintaining this, it's a fun project!

**Comment by adam-lynch** [comment]
I think I fixed this last week. It seems OK to me now. Please let me know if I'm wrong (but hard refresh just to be safe).

>Thanks for maintaining this, it's a fun project!

Thank you for helping!

**Comment by alansartorio** [comment]
Works great after a hard refresh!
