### ISSUE TITLE
Needs to filter out more "objects"

### ISSUE THREAD

**Issue by adam-lynch** [adam-lynch/back-of-your-hand#18]
From Hacker News:

>[...]Also it was quizzing me on park trails. And I just got an underwater tunnel at the zoo. I guess those are technically named ways in some manner of speaking, but they're definitely not streets with signs.All that aside, this is really fun! Personal best 470/500. I wish I could make it longer; n=5 is a small sample and my scores vary tremendously from one run to the next.

\- myself248, https://news.ycombinator.com/item?id=30735746

>I enjoyed it! worked reasonably well for the city I tried. I did have a few nitpicks, but they are mostly datasource related as opposed to anything you can control - the several rounds i played included a pedway system, several walking trails, and a private driveway. Only change I might suggest making is the radius of the pin - getting a 99/100 for being 6m off because the pin didnt go exactly where I thought it was. Or is there any way for the pin to snap to an object?

\- SECProto, https://news.ycombinator.com/item?id=30737042

>> Can you give me the coordinates you played in? I will review the "objects".

>Here's the osm for the pedway object, labelled a footpath. https://www.openstreetmap.org/relation/11909462. Here's one of the trails: https://www.openstreetmap.org/way/511807176

\- SECProto, https://news.ycombinator.com/item?id=30737448

**Comment by adam-lynch** [comment]
@johrpan I actually use that already. I even exclude sub-categories of `highway`. See here: https://github.com/adam-lynch/back-of-your-hand/blob/main/source/utilities/getData.ts#L56-L89

What's to be done now is to look into specific complaints and see if it's a sub-category that be filtered. If not, then maybe there's some other way to exclude it. There's a chance it's something we'd want to keep 99% of the time though / an OSM data issue.

Tools that help:

- [OpenStreetMap Nominatim](https://nominatim.openstreetmap.org/)
- [OpenStreetMap search](https://www.openstreetmap.org/)
- [Overpass Turbo](https://overpass-turbo.eu/)

**Comment by johrpan** [comment]
@adam-lynch Sorry, my bad.

However, I think that lots of those can and/or should be left out. By following the descriptions in the [OpenStreetMap Wiki](https://wiki.openstreetmap.org/wiki/Key:highway) and experimenting a bit using the [Overpass API](https://overpass-turbo.eu/) – thanks for the link – I found the following set of highway values that seems to exactly match my expectations, at least in my home area:

 - motorway
 - trunk
 - primary
 - secondary
 - tertiary
 - unclassified
 - residential
 - living_street
 - pedestrian
 
In my opinion, this would be everything that matches the definition of being a "street".

**Comment by adam-lynch** [comment]
I've removed a good few (of the ones you didn't list) to begin with. Some were good (e.g. service, steps) in Cork, Ireland; https://overpass-turbo.eu/s/1haX

**Comment by adam-lynch** [comment]
Reminder: only elements with a name are used. A catch might be if in some countries the OSM data has bad names like "Steps" for `steps`

**Comment by adam-lynch** [comment]
I've confirmed that all of the original reports are fixed
