### ISSUE TITLE
Filter out smaller streets?

### ISSUE THREAD

**Issue by adam-lynch** [adam-lynch/back-of-your-hand#19]
I'm not so sure about this one. It came up a bit on Hacker News;

>Depends on what you're looking for but I think this would be more fun if it excluded very tiny streets, like minimum length. I got what is essentially a driveway for two houses that's not paved or labeled, nobody would know it's name (or that it was a named street even) unless you lived on it or next door to it. (I live next door to it). Might be less fun if someone got that on their first try.But, again, some people are looking for a challenge, so maybe make it an option.

\- astura, https://news.ycombinator.com/item?id=30735234

>I basically failed because almost all of the selections were random tiny roads in subdivisions (thanks Atlanta sprawl). Got all the roads with thru traffic though!

\- kfajdsl, https://news.ycombinator.com/item?id=30735457

>Same area. There's a hundred or more tiny subdivision roads for every major road. It would be better to omit roads under a certain length entirely since it's not reasonable for someone to know all the roads in a subdivision they never have a reason to visit.

\- Kye, https://news.ycombinator.com/item?id=30736483

>I did where I live now, and only got 100/500 (perfect score on the major road, no idea where the rest were). I did my childhood home and got 99/500. My suggestion would be to stick to majors and semi-majors (longer through streets). It would be more fun that way.[...]

\- jedberg, https://news.ycombinator.com/item?id=30736012

This is related to #5. Maybe there's a way to factor length into the scoring and avoid a setting, not sure.

**Comment by llacb47** [comment]
I think filtering streets by their classification would be a better approach, and perhaps letting the user choose which classifications are included. https://wiki.openstreetmap.org/wiki/Key:highway#Values

**Comment by adam-lynch** [comment]
@llacb47 I agree

**Comment by adam-lynch** [comment]
https://github.com/adam-lynch/back-of-your-hand/commit/495efa7142172e69f7a3dceb31ae93267651dd07

**Comment by liamengland1** [comment]
Awesome! Changes look good
