### ISSUE TITLE
The same streets come up too much

### ISSUE THREAD

**Issue by adam-lynch** [adam-lynch/back-of-your-hand#20]
This was mentioned a few times in [Hacker News post comments](https://news.ycombinator.com/item?id=30733339#30738345)

**Comment by marcandre** [comment]
They even come twice in a round, and there must be over 50 streets in my surroundoing...

<img width="372" alt="image" src="https://user-images.githubusercontent.com/33770/159144575-333fc14f-e1b2-4c23-bf6c-8bf33f64c36f.png">

**Comment by adam-lynch** [comment]
Will fix @marcandre, thanks
