### ISSUE TITLE
Consider limiting to just street names

### ISSUE THREAD

**Issue by matkoniecz** [adam-lynch/back-of-your-hand#3]
Hopefully gift worked well!

It certainly worked well for me and my sister :)

Not sure whatever you want to improve it further and deal with things likely not mattering in your region but...

Right now everything with `highway` is taken. It includes for example named bus stops (`highway=bus_stop`).

Limiting it to list of valid value may be useful.

List of road value:

> "motorway", "motorway_link", "trunk", "trunk_link", "primary", "primary_link", "secondary", "secondary_link", "tertiary", "tertiary_link", "unclassified", "residential", "living_street", "pedestrian", "service", "track"

List of values for paths/cycleways/etc:

> "footway", "cycleway", "path", "bridleway", "steps"

And there are special values: "road" (unknown type, not yet classified) and "proposed" (not existing) and "construction" (under construction)

**Comment by adam-lynch** [comment]
Dzień dobry :)

That's great to hear!

>Not sure whatever you want to improve it further and deal with things likely not mattering in your region but...

I don't plan on spending a lot of time on it but if there are small changes I can make I will (or anyone who is willing to contribute via pull-request too).

>It includes for example named bus stops (highway=bus_stop).

Oh, I didn't know that, thanks. It seems to not be used in Cork, London, Brussels, but I do see it in Kraków.

I will update it to exclude that but I do want to keep non-roads like walking paths/trails, even "cycleway" for example. As long as they have a name though.

**Comment by Jakuje** [comment]
For me, it picked up this mtb trail instead of a streat name:

https://www.openstreetmap.org/way/81400234

Indeed, I knew where to look for that one, but using the path name is usually not a good idea when looking for street names ;)

**Comment by Jakuje** [comment]
I would be for excluding the path too as I mentioned in the last comment.
