### ISSUE TITLE
Close hit should be worth 100 points

### ISSUE THREAD

**Issue by matkoniecz** [adam-lynch/back-of-your-hand#4]
Currently very, very close hit may be not worth 100 points - and spending time on fine-tuning pin position is a bit silly.

Maybe for distances up to say 50-70 meters should be worth full 100 points?

**Comment by adam-lynch** [comment]
Thanks for the feedback. I agree. I thought I had made it so you need to be within 5/10 metres but I guess I didn't. 

50-70 sounds like a lot to me. If two people are competing and one is more accurate, I want to reward them, but not so minutely that they have to be extremely careful, just careful. This would be especially annoying when using touch as it's imprecise.

So what I might do is base it on the size of a finger tap (at a close zoom level).

**Comment by matkoniecz** [comment]
50-70 was what was typical maximum offset in case where I (or someone else) knew exactly where street is but have not bothered with micromanaging of pin position.

**Comment by matkoniecz** [comment]
My issue is invalid, we played on the laptop and failed to use zooming.
