### ISSUE TITLE
Close settings when map is touched

### ISSUE THREAD

**Issue by adam-lynch** [adam-lynch/back-of-your-hand#52]
If you click/tap the "Settings" button and then interact with the map in any way, it should collapse/hide the settings so the map is as big as possible.

This would be helpful when the screen is small (particularly when the context panel on the bottom of the screen). I probably wouldn't bother doing it when the screen is large, it might be off-putting.

**Comment by Yogeshp0012** [comment]
I can work on this.

**Comment by adam-lynch** [comment]
@Yogeshp0012 ok thanks. Let me know if you've any questions

**Comment by adam-lynch** [comment]
Closed via #53
